Add JFlex Grammar And Parser
morganey-lang/morganey-intellij-plugin pull request #18
Opened 2016-11-18 19:15 UTC by 06needhamt

Close #17 

I've been very busy with my studies so I have not had chance to work on this for a while. However I had some free time. I've managed to get a JFlex Grammar and Parser to generate using the available BNF. When i get the chance i will attempt to implement #3 and #4 

@ForNeVeR @rexim Please Review

Also See https://github.com/morganey-lang/Morganey/issues/246

2016-11-19 04:44 UTC, ForNeVeR requested changes
Okay, we need to discuss the changes a little bit more. Generally I don't think that we should merge breaking and unfinished changes _if the `master` branch works in its current state_; probably we'll need to polish this PR a little bit more before merge (e.g. implement #3 or #4 or at least make it work without too much errors). **But I want to hear your opinions, guys.**

I'll also inspect the line endings in the repo and in the PR and drop a line in the comments.

2016-11-19 04:44 UTC, ForNeVeR commented on src/main/kotlin/me/rexim/morganey/plugin/filetype/MorganeyFileType.kt
>  }
The changes in this file are looking a bit strange to me. I suspect that some line ending conversion was involved. I'll inspect the situation more closely; please don't merge before that.

2016-11-19 04:44 UTC, ForNeVeR commented on src/main/kotlin/me/rexim/morganey/plugin/lexer/MorganeyLexer.kt
> +}
This file looks as it's not in a working state now. Aren't you changing something that was working into something that doesn't work?

I have no prejudice against that action, but if so, then we need to discuss that. I think I saw @rexim using the plugin on his streams, and that means we generally shouldn't break the plugin in `develop` branch.

2016-11-19 04:44 UTC, ForNeVeR commented on src/main/resources/META-INF/plugin.xml
>  </idea-plugin>
I suspect that this file was involved in the same line ending conversion; will investigate.

2016-11-19 04:44 UTC, ForNeVeR commented on src/main/kotlin/me/rexim/morganey/plugin/lexer/generated/_MorganeyLexer.java
> +}
Are you sure that `generated` files should go into the repository? How exactly were they generated? Could we make additional build step to generate them?

2016-11-19 04:59 UTC, ForNeVeR commented on src/main/kotlin/me/rexim/morganey/plugin/filetype/MorganeyFileType.kt
>  }
Okay. According to my inspection, current file in the `master` branch contains proper `\n` line endings, and your commit has changed them to `\r\n`. Please fix that in all the files and force-push the commit.

2016-11-19 10:08 UTC, 06needhamt commented on src/main/kotlin/me/rexim/morganey/plugin/lexer/MorganeyLexer.kt
> +}
Oops forgot to implement this

2016-11-19 10:09 UTC, 06needhamt commented on src/main/kotlin/me/rexim/morganey/plugin/filetype/MorganeyFileType.kt
>  }
I think I Fixed The Issue

2016-11-19 10:09 UTC, 06needhamt commented on src/main/kotlin/me/rexim/morganey/plugin/lexer/MorganeyLexer.kt
> +}
Oops forgot to implement this

2016-11-19 10:10 UTC, 06needhamt commented on src/main/kotlin/me/rexim/morganey/plugin/lexer/generated/_MorganeyLexer.java
> +}
I'm not sure will investigate further

2016-11-19 10:37 UTC, 06needhamt commented on src/main/kotlin/me/rexim/morganey/plugin/lexer/generated/_MorganeyLexer.java
> +}
As of now i see no way to generate these files on build without causing errors i tried adapting the code that the rust IntelliJ plugin uses but hundreds of errors occur on generation 

```
task generateMorganeyPsiAndParser(type: JavaExec) {
    doFirst {
        delete file("src/main/kotlin/me/rexim/morganey/plugin/parser/generated/psi/")
    }
    ext.src     = "src/main/kotlin/me/rexim/morganey/plugin/resources/morganey.bnf"
    ext.dstRoot = "src/main/kotlin/me/rexim/morganey/plugin/parser/generated"

    main = "org.intellij.grammar.Main"

    args = [ dstRoot, file(src) ]

    inputs  .file   file(src)
    outputs .dir    fileTree(dir: dstRoot + '/me/rexim/morganey/plugin/', include: '**/*.java')

    classpath (configurations.compile + files('lib/grammar-kit.jar'))
}
```

2016-11-19 10:39 UTC, ForNeVeR commented on src/main/kotlin/me/rexim/morganey/plugin/lexer/generated/_MorganeyLexer.java
> +}
Then, for now, please write a simple instruction about the way you finally generated them. I think that it's okay to keep generated files in the repo if and only if it's no easy way of generating them again.

But in case we'll want to (re)generate them later, we'll need a complete manual about how to do that!

2016-11-19 10:42 UTC, ForNeVeR requested changes
Alright, all of my other suggestions were addressed, so currently this PR only lacks an instruction on how to generate the files from the `generated` directory. Everything else is (generally) LGTM 👍

2016-11-19 15:06 UTC, rexim approved these changes
No remarks except @ForNeVeR's ones

2016-11-19 18:02 UTC, 06needhamt commented
I've had a think about it and as far as i can tell the files are never going to change unless the syntax of Morganey changes so its probably not that big of a deal just including them in the repository.

Let me know what you guys think @rexim @ForNeVeR

2016-11-19 18:13 UTC, rexim commented
> I've had a think about it and as far as i can tell the files are never going to change unless the syntax of Morganey changes so its probably not that big of a deal just including them in the repository.

I believe that this was already addressed by @ForNeVeR in https://github.com/morganey-lang/morganey-intellij-plugin/pull/18#discussion_r88777252 and I completely agree with him.

2016-11-19 18:39 UTC, 06needhamt commented on src/main/kotlin/me/rexim/morganey/plugin/lexer/generated/_MorganeyLexer.java
> +}
The files can be generated by installing the GrammarKit plugin into IntelliJ right clicking on the `morganey.bnf` file and clicking the following options in this order `Generate JFLex Lexer`, `Generate Parser Code` and `Generate Parser` 
See Screenshot Below
![bnf](https://cloud.githubusercontent.com/assets/4162227/20457640/5e5181e2-ae87-11e6-980f-ad4576ce8940.PNG)

2016-11-19 18:39 UTC, 06needhamt commented
@rexim Ah i missed that comment i have added instructions

2016-11-20 05:15 UTC, ForNeVeR commented on src/main/kotlin/me/rexim/morganey/plugin/lexer/generated/_MorganeyLexer.java
> +}
@06needhamt alright, could you please add this information into `README`?

2016-11-20 09:07 UTC, 06needhamt commented on src/main/kotlin/me/rexim/morganey/plugin/lexer/generated/_MorganeyLexer.java
> +}
I added the instructions to CONTRIBUTING.MD and mentioned them in README.MD

2016-11-20 09:26 UTC, ForNeVeR requested changes

2016-11-20 09:26 UTC, ForNeVeR commented on CONTRIBUTING.md
> +[Imgur](http://i.imgur.com/zwdxuHj.png)
Pro hint™: add a `!` at the beginning of that line to embed the image there!

2016-11-20 12:18 UTC, 06needhamt commented on CONTRIBUTING.md
> +[Imgur](http://i.imgur.com/zwdxuHj.png)
Cool I didn't know that

2016-11-20 12:21 UTC, 06needhamt commented on CONTRIBUTING.md
> +[Imgur](http://i.imgur.com/zwdxuHj.png)
Done

2016-11-20 13:07 UTC, ForNeVeR approved these changes
LGTM :+1:

2016-11-20 13:15 UTC, merged

2016-11-20 13:15 UTC, 06needhamt commented
@rexim @ForNeVeR Thanks for the review